### ISSUE TITLE
Nginx & php5-fpm, Debian Jessie, can't Authorized new Client

### ISSUE THREAD

**Issue by zoide** [cweiske/grauphel#34] opened 2016-01-13 12:02 UTC
Hi there. 
I cannot authorize any new client with grauphel. A previously registered tomdroid still works fine.

Infrastructure:
Internet -> nignx-loadbalancer -> onwcloudhost with nignx and php-fpm

Owncloud Host: 
Debian Jessie
owncloud 8.2.x (8.2.1, 8.2.2)
grauphel (master, 0.6.1)

Clients:
tomdroid
tomboy 1.15.4
In Tomboy, I get "Server not responding".
Both clients do not redirect to the authorization page.

Servermessage: nothing in owncloud's logs
nginx logs:

```
x.x.x.x - cpalmer [13/Jan/2016:12:56:09 +0100] "PROPFIND /remote.php/webdav/KMM%20Portal HTTP/1.0" 404 238 "-" "Mozilla/5.0 (Macintosh) mirall/2.0.1"
x.x.x.x - - [13/Jan/2016:12:56:09 +0100] "GET /index.php/apps/grauphel/api/1.0 HTTP/1.0" 200 326 "-" "-"
x.x.x.x - - [13/Jan/2016:12:56:09 +0100] "GET /index.php/apps/grauphel/oauth/request_token HTTP/1.0" 405 0 "-" "-"
```

I guess this is somehow related to the last patches with the Authorization headers not being passed.
I have 

```
    fastcgi_pass_header Authorization;
```

in the loadbalancer's and onwcloud host's nginx config.

Thanks for any help.

**Comment by harryhb** [comment] 2016-03-27 17:21
I can confirm: connecting with (new) clients is currently not possible

Setup:
Debian stable; nginx - php5-fpm
Owncloud 9.0.0
Grauphel 0.6.2

Tomboy: "Server not responding"
- In owncloud logs: 
  `Error  PHP Missing argument 1 for OCA\Grauphel\Lib\TokenStorage::__construct(), called in /var/www/owncloud/apps/grauphel/lib/dependencies.php on line 69 and defined at /var/www/owncloud/apps/grauphel/lib/tokenstorage.php#34`
- https://cloud.xxx.yy/index.php/apps/grauphel/oauth/authorize
  `oauth_token missing`

**Comment by cweiske** [comment] 2016-03-27 17:57
@harryhb: Which PHP version, which php-oauth version?

The error message is fixed in git now; but it has nothing to do with this issue here.

**Comment by harryhb** [comment] 2016-03-27 19:04
PHP 5.6.17-0+deb8u1

php-oauth installed through apt: Version: 1.2.3-1+b1
Installed through pecl too (v 1.2.3), no difference.

This is the first time and only application using oauth on this server, but it seems oauth is correctly loaded, attached is phpinfo-section.

![oauth](https://cloud.githubusercontent.com/assets/18102854/14067182/1bc34dde-f45f-11e5-97b9-128b8a61ad47.png)

If I can / should test something else, I am happy to do so...
Tomdroid is also failing to connect.

**Comment by cweiske** [comment] 2016-03-28 18:35
@harryhb: I already tried reproducing the issue here locally with nginx and php-fpm but failed. The only thing that could actually help is SSH access to a server where this issue occurs, with the ability to modify the grauphel source code. I could then debug the issue. If you're willing to give me that access to your server, drop me a mail to cweiske+grauphel@cweiske.de

**Comment by harryhb** [comment] 2016-03-28 20:16
**@cweiske:** I was preparing your access and I found the cause of the error.

I had the checkbox enabled to restrict the use for a group of users (in "apps"). Unchecking enables the oauth function...

Do not know if this is a bug or a feature? :-) 

Thank you for this great piece of software and the support!

**Comment by cweiske** [comment] 2016-03-29 15:25
I've dug to the root of the cause:
- ownCloud completely blocks anything on an app when it's only available to some users
- Note sync clients make requests as unauthenticated (not logged in, `null`) users and thus don't even have a chance to access the app.

There is nothing I can do here except making a note in the README - see 07939af.

---

@zoide: Did you also have the app only available for a selected group of users? I guess not.

**Comment by zoide** [comment] 2016-03-30 15:28
Hi, sorry for the answer-delay.

For me this issue was resolved as soon as I grabbed the version from here: http://git.cweiske.de/grauphel.git/

Seems that github and that repo were out of sync.

**Comment by zoide** [comment] 2016-03-30 15:29
I didn't even know that you can restrict apps to certain users.

**Closed as completed** 2016-03-30 18:25 UTC
