### ISSUE TITLE
App gets disabled periodically from Nextcloud

### ISSUE THREAD

**Issue by grosjo** [cweiske/grauphel#71] opened 2019-02-05 06:13 UTC
Hi,
I have to periodically "enable" the Graphel app, as it gets disabled periodically.
Nextcloud 15.0.2

**Comment by cweiske** [comment] 2019-02-07 18:19
How fast does this happen?
Does the nextcloud logfile have any entries about that?

**Comment by grosjo** [comment] 2019-02-08 05:29
There is no log, but I note it as my Android ou Tomboy (laptop) shows error (parsing error), and then I see on NextCloud that the app is disabled, and I need to  re "enable" the app on Nextcloud.

This problem appears only on Grauphel

I sent you several  emails about it for a year or so already

**Comment by cweiske** [comment] 2019-02-08 16:59
> There is no log

Nextcloud has a log file, it's usually in the `data` folder.

> I sent you several emails about it for a year or so already

Yes, I got one e-mail from you end of last year and replied.

**Comment by grosjo** [comment] 2019-02-08 17:15
yes there is a log, but what I wanted to say : "There is nothing in hte log"
no, I have never got any feedback from you.
Anyway, how to resolve this ?

**Comment by cweiske** [comment] 2019-02-10 10:45
I suggest that you increase the logging level and then reproduce the problem. Increase the log level until you get something relevant in the logs.

Also, check your web server error log and find out which status code is sent on the erroneous page.

https://docs.nextcloud.com/server/15/admin_manual/configuration_server/logging_configuration.html

----

btw, I re-send the mail to you from last year. You can check if it was moved to the spam folder.

**Comment by grosjo** [comment] 2019-02-13 09:23
I put the low level log (=0)
THe app gets disabled without any specific entry in the log

**Comment by cweiske** [comment] 2019-02-13 21:57
I'm out of ideas. Sorry.

**Comment by grosjo** [comment] 2019-02-16 23:24
But you are the one writing the code

**Comment by grosjo** [comment] 2019-02-16 23:24
how dot this gets disabled  ?

**Comment by cweiske** [comment] 2019-02-17 07:22
Grauphel contains no code that disables grauphel itself.
-- 
Regards/Mit freundlichen Grüßen
Christian Weiske

**Comment by grosjo** [comment] 2019-02-19 20:15
Maybe this is the error : 
{"reqId":"jXAPskpqvAfMB3iKAbbx","level":3,"time":"2019-02-18T01:30:02+00:00","remoteAddr":"","user":"--","app":"no app in context","method":"","url":"--","message":{"Exception":"Exception","Message":"Error 47 interacting with memcached : SERVER HAS FAILED AND IS DISABLED UNTIL TIMED RETRY","Code":0,"Trace":[{"file":"\/data\/web\/s

**Comment by grosjo** [comment] 2019-02-19 20:19
If this is the cause, there is a PHP code to adjust according to the link (as all the next cloud is otherwise working very fine)
https://serverfault.com/questions/470951/how-to-debug-memcached-server-has-failed-and-is-disabled-until-timed-retry-err

**Comment by cweiske** [comment] 2019-02-19 21:04
grauphel itself does not use memcached.

**Comment by grosjo** [comment] 2019-02-20 04:34
Maybe but it may be also that upon failure, the app is not re-instanciated 
correctly, isn't it ?

**Comment by cweiske** [comment] 2019-03-04 22:46
- which webserver do you use, in which version?
- which PHP version?
- how is PHP connected to the webserver software?
- which memcached version?

**Comment by grosjo** [comment] 2019-03-05 04:54
Apache 2.4.38
PHP 7.2.15 ( https://grosjo.net/info.php )
mod_php
memcached 1.5.12 (libmemcached 1.0.18)

**Comment by grosjo** [comment] 2019-03-17 09:54
Any update ?

**Comment by cweiske** [comment] 2019-03-17 17:03
No. Your versions look current enough. I have no idea why grauphel could get disabled.

**Comment by cweiske** [comment] 2019-03-19 09:57
Others have the same problem with other extensions:

- https://help.nextcloud.com/t/does-nextcloud-automatically-disable-apps/35368 (unsolved)
- https://help.nextcloud.com/t/app-keeps-getting-disabled/25165/ (file ownership/permission problems)

**Comment by grosjo** [comment] 2019-03-30 10:03
one says "permissions are not right" but no such messages and permissions are exatly the same as nextcloud.
logs shows nothing

**Comment by cweiske** [comment] 2019-03-31 19:32
I'm closing this issue because I cannot help you, and I cannot stand getting any more comments from you. Either debug the problem on your own or stop trying to use grauphel.

**Closed as completed by cweiske** 2019-03-31 19:32 UTC
