### ISSUE TITLE
Tomboy (Linux) 1.15.4 does not sync

### ISSUE THREAD

**Issue by rigelhope** [cweiske/grauphel#15] opened 2014-12-26 00:35 UTC
I couldnt get Tomboy to sync using a really old set of notes i dug up, (but it works fine with Tomdroid 0.7.5). relevant debug output is below. Unsure of where to start debugging. Would try with gnote but it doesnt have API sync.

I have not yet tried to downgrade my version to a known-good one ( 1.15.2 is stated to work in the README)

Suggestions appreciated. I have not yet filed a bug report for Tomboy.

```
[DEBUG 15:33:39.191] SyncThread using SyncServiceAddin: Tomboy Web
[DEBUG 15:33:39.197] Building web request for URL: https://my.domain/owncloud/index.php/apps/grauphel/api/1.0/
[DEBUG 15:33:40.604] Building web request for URL: https://my.domain/owncloud/index.php/apps/grauphel/api/1.0/username
[DEBUG 15:33:40.672] 8
[DEBUG 15:33:40.673] Sync: GetNoteUpdatesSince rev -1
[DEBUG 15:33:40.674] Building web request for URL: https://my.domain/owncloud/index.php/apps/grauphel/api/1.0/username/notes?include_notes=true

(Tomboy:8234): GLib-CRITICAL **: Source ID 182 was not found when attempting to remove it

(Tomboy:8234): GLib-CRITICAL **: Source ID 172 was not found when attempting to remove it

(Tomboy:8234): GLib-CRITICAL **: Source ID 194 was not found when attempting to remove it

(Tomboy:8234): GLib-CRITICAL **: Source ID 56 was not found when attempting to remove it

(Tomboy:8234): GLib-CRITICAL **: Source ID 48 was not found when attempting to remove it
[ERROR 15:33:41.223] Synchronization failed with the following exception: a name did not start with a legal character 38 (&)  Line 6, position 2.
  at Mono.Xml2.XmlTextReader.ReadName (System.String& prefix, System.String& localName) [0x00000] in <filename unknown>:0 
  at Mono.Xml2.XmlTextReader.ReadName () [0x00000] in <filename unknown>:0 
  at Mono.Xml2.XmlTextReader.ReadEntityReference (Boolean ignoreEntityReferences) [0x00000] in <filename unknown>:0 
  at Mono.Xml2.XmlTextReader.ReadReference (Boolean ignoreEntityReferences) [0x00000] in <filename unknown>:0 
  at Mono.Xml2.XmlTextReader.ReadText (Boolean notWhitespace) [0x00000] in <filename unknown>:0 
  at Mono.Xml2.XmlTextReader.ReadContent () [0x00000] in <filename unknown>:0 
  at Mono.Xml2.XmlTextReader.Read () [0x00000] in <filename unknown>:0 
  at System.Xml.XmlTextReader.Read () [0x00000] in <filename unknown>:0 
  at Tomboy.Sync.NoteUpdate..ctor (System.String xmlContent, System.String title, System.String uuid, Int32 latestRevision) [0x00000] in <filename unknown>:0 
  at Tomboy.WebSync.WebSyncServer.GetNoteUpdatesSince (Int32 revision) [0x00000] in <filename unknown>:0 
  at Tomboy.Sync.SyncManager.SynchronizationThread () [0x00000] in <filename unknown>:0 

(Tomboy:8234): GLib-CRITICAL **: g_source_remove: assertion 'tag > 0' failed
[DEBUG 15:49:11.887] SyncThread using SyncServiceAddin: Tomboy Web
[DEBUG 15:49:11.887] Building web request for URL: https://my.domain/owncloud/index.php/apps/grauphel/api/1.0/
[DEBUG 15:49:12.183] Building web request for URL: https://my.domain/owncloud/index.php/apps/grauphel/api/1.0/username
[DEBUG 15:49:12.239] 8
[DEBUG 15:49:12.240] Sync: GetNoteUpdatesSince rev -1
[DEBUG 15:49:12.240] Building web request for URL: https://my.domain/owncloud/index.php/apps/grauphel/api/1.0/username/notes?include_notes=true

(Tomboy:8234): GLib-CRITICAL **: Source ID 198 was not found when attempting to remove it

(Tomboy:8234): GLib-CRITICAL **: Source ID 200 was not found when attempting to remove it

(Tomboy:8234): GLib-CRITICAL **: Source ID 204 was not found when attempting to remove it

(Tomboy:8234): GLib-CRITICAL **: Source ID 453 was not found when attempting to remove it

(Tomboy:8234): GLib-CRITICAL **: Source ID 203 was not found when attempting to remove it

(Tomboy:8234): GLib-CRITICAL **: Source ID 454 was not found when attempting to remove it

(Tomboy:8234): GLib-CRITICAL **: Source ID 459 was not found when attempting to remove it
[ERROR 15:49:12.813] Synchronization failed with the following exception: a name did not start with a legal character 38 (&)  Line 6, position 2.
  at Mono.Xml2.XmlTextReader.ReadName (System.String& prefix, System.String& localName) [0x00000] in <filename unknown>:0 
  at Mono.Xml2.XmlTextReader.ReadName () [0x00000] in <filename unknown>:0 
  at Mono.Xml2.XmlTextReader.ReadEntityReference (Boolean ignoreEntityReferences) [0x00000] in <filename unknown>:0 
  at Mono.Xml2.XmlTextReader.ReadReference (Boolean ignoreEntityReferences) [0x00000] in <filename unknown>:0 
  at Mono.Xml2.XmlTextReader.ReadText (Boolean notWhitespace) [0x00000] in <filename unknown>:0 
  at Mono.Xml2.XmlTextReader.ReadContent () [0x00000] in <filename unknown>:0 
  at Mono.Xml2.XmlTextReader.Read () [0x00000] in <filename unknown>:0 
  at System.Xml.XmlTextReader.Read () [0x00000] in <filename unknown>:0 
  at Tomboy.Sync.NoteUpdate..ctor (System.String xmlContent, System.String title, System.String uuid, Int32 latestRevision) [0x00000] in <filename unknown>:0 
  at Tomboy.WebSync.WebSyncServer.GetNoteUpdatesSince (Int32 revision) [0x00000] in <filename unknown>:0 
  at Tomboy.Sync.SyncManager.SynchronizationThread () [0x00000] in <filename unknown>:0 

(Tomboy:8234): GLib-CRITICAL **: g_source_remove: assertion 'tag > 0' failed
[DEBUG 15:52:14.257] SyncThread using SyncServiceAddin: Tomboy Web
[DEBUG 15:52:14.257] Building web request for URL: https://my.domain/owncloud/index.php/apps/grauphel/api/1.0/
[DEBUG 15:52:14.723] Building web request for URL: https://my.domain/owncloud/index.php/apps/grauphel/api/1.0/username
[DEBUG 15:52:14.777] 8
[DEBUG 15:52:14.778] Sync: GetNoteUpdatesSince rev -1
[DEBUG 15:52:14.778] Building web request for URL: https://my.domain/owncloud/index.php/apps/grauphel/api/1.0/username/notes?include_notes=true

(Tomboy:8234): GLib-CRITICAL **: Source ID 582 was not found when attempting to remove it

(Tomboy:8234): GLib-CRITICAL **: Source ID 594 was not found when attempting to remove it

(Tomboy:8234): GLib-CRITICAL **: Source ID 581 was not found when attempting to remove it

(Tomboy:8234): GLib-CRITICAL **: Source ID 41 was not found when attempting to remove it

(Tomboy:8234): GLib-CRITICAL **: Source ID 171 was not found when attempting to remove it

(Tomboy:8234): GLib-CRITICAL **: Source ID 451 was not found when attempting to remove it

(Tomboy:8234): GLib-CRITICAL **: Source ID 11 was not found when attempting to remove it
[ERROR 15:52:15.197] Synchronization failed with the following exception: a name did not start with a legal character 38 (&)  Line 6, position 2.
  at Mono.Xml2.XmlTextReader.ReadName (System.String& prefix, System.String& localName) [0x00000] in <filename unknown>:0 
  at Mono.Xml2.XmlTextReader.ReadName () [0x00000] in <filename unknown>:0 
  at Mono.Xml2.XmlTextReader.ReadEntityReference (Boolean ignoreEntityReferences) [0x00000] in <filename unknown>:0 
  at Mono.Xml2.XmlTextReader.ReadReference (Boolean ignoreEntityReferences) [0x00000] in <filename unknown>:0 
  at Mono.Xml2.XmlTextReader.ReadText (Boolean notWhitespace) [0x00000] in <filename unknown>:0 
  at Mono.Xml2.XmlTextReader.ReadContent () [0x00000] in <filename unknown>:0 
  at Mono.Xml2.XmlTextReader.Read () [0x00000] in <filename unknown>:0 
  at System.Xml.XmlTextReader.Read () [0x00000] in <filename unknown>:0 
  at Tomboy.Sync.NoteUpdate..ctor (System.String xmlContent, System.String title, System.String uuid, Int32 latestRevision) [0x00000] in <filename unknown>:0 
  at Tomboy.WebSync.WebSyncServer.GetNoteUpdatesSince (Int32 revision) [0x00000] in <filename unknown>:0 
  at Tomboy.Sync.SyncManager.SynchronizationThread () [0x00000] in <filename unknown>:0 

(Tomboy:8234): GLib-CRITICAL **: g_source_remove: assertion 'tag > 0' failed
```

**Comment by cweiske** [comment] 2014-12-26 08:57
This seems to be an error during XML parsing. Tomboy stores the its notes as XML; this is the only place I know where this error could happen. (Synchronization with grauphel uses JSON, not XML).

So I would think that one of the note xml files is broken:

```
Synchronization failed with the following exception: a name did not start with a legal character 38 (&) Line 6, position 2.
```

Try to open all the notes and see if that works.
Another try: Back the notes up and create a new note and try to sync that single note.

**Comment by rigelhope** [comment] 2014-12-26 09:29
none of my notes have '&' in the title at all, so i'm not sure where that error is coming from either. the debug log was from two sync attempts and i noticed the errors were being thrown based on different notes each time, and that was puzzling.

i did clear the notes on the server and Tomboy appears to be syncing successfully now.

I did notice that pressing the "delete all notes from remote" button on the Tomdroid clients didnt clear the remote notes. Unsure if that's expected/desired.

Thanks for your help.

**Comment by cweiske** [comment] 2014-12-26 19:19
I forgot that the note content actually is XML. So the note content was broken somehow.

It could be that either the client that stored the notes on the server broke them, or grauphel had some encoding issues.

Since you removed all notes, you probably do not have a backup of the grauphel notes database...

---

I did not yet try the "delete all notes from remote" button; didn't even know it existed.

**Comment by rigelhope** [comment] 2014-12-27 20:08
i dont have a backup of the grauphel db but i did back up all my notes on my devices before nuking them, so i suppose i could try and add them one by one to see which of them cause it to choke. sounds like a big PITA though.

**Comment by cweiske** [comment] 2014-12-28 06:17
Maybe you can send a zip file or so with all of them to me, then I could look at them to see if I can find anything. cweiske+github.com-issues@cweiske.de

Which devices and tomboy software versions do you have?

**Comment by Zotan** [comment] 2015-01-14 23:15
I've just seen this with Tomboy 1.15.4 on OpenSUSE. I couldn't sync the two default notes that are created on first run. After deleting them, I can sync the notes that I have created so far.

**Comment by cweiske** [comment] 2015-01-15 22:02
I tried to reproduce the error, but cannot - even after deleting `~/.local/share/tomboy` and `~/.config/tomboy` and syncing to a fresh owncloud user.

**Comment by cweiske** [comment] 2015-03-11 07:35
Closing because I cannot reproduce the issue.

**Closed as completed by cweiske** 2015-03-11 07:35 UTC
